version: '2.1'
services:
    metabase:
        restart: "always"
        image: metabase/metabase
        environment:

            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=odoo
            - MB_DB_PASS=odoo
            - MB_DB_HOST=db
        ports:
            - 3000:3000
        networks:
            goro:
        labels:
            - traefik.enable=true
            - traefik.frontend.port=3000
        depends_on:
            - db
            - dns
    db:
        image: postgres:14
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - pg_data:/var/lib/postgresql/data/pgdata
        networks:
            goro:
        ports:
           - 54320:5432
    aeroo:
        image: adhoc/aeroo-docs
        restart: unless-stopped
        networks:
            goro:
    dns:
        image: cytopia/bind:alpine-0.30
        environment:
            DNS_A: '*=172.30.16.1'
            DNS_FORWARDER: 127.0.0.11
        networks:
            goro:
                ipv4_address: 172.30.16.10
    odoo:
        # user: root
        # build:
        #     context: ./data
        #     dockerfile: Dockerfile
        image: filoquin/odoo:16.0
        depends_on:
            - db
            - dns
            - aeroo
        volumes:
            - ./custom_modules:/opt/odoo/src/custom-addons
            - default:/home/odoo/src
            - odoo_data:/home/odoo/data
        labels:
            - traefik.enable=true
            - traefik.frontend.port=8069
            - traefik.frontend.rule=HostRegexp:{catchall:.*},{subdomain:[a-z0-9-_]+}.{catchall:.*}
            - traefik.frontend.priority=5
            # - traefik.longpolling.port=8072
            # - traefik.longpolling.frontend.rule=HostRegexp:{catchall:.*},{subdomain:[a-z0-9-_]+}.{catchall:.*};PathPrefix:/longpolling/
            # - traefik.longpolling.priority=10
            - traefik.backend.loadbalancer.stickiness=true
            - traefik.backend.loadbalancer.method=drr
            # traefik.frontend.redirect.regex: $strTraefikRedirectRegex
            # traefik.frontend.redirect.replacement: $strTraefikRedirectReplacement
        environment:
            CUSTOM_CONFIG: |-
                [options]
            CUSTOM_REQUIREMTNS: |-
                # custom pip librearies
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                # pip install --user --no-cache-dir -e /home/odoo/custom/odoo
                # pip install --user --no-cache-dir pyopenssl
            DBFILTER: wwww.casagoro.com.ar
            MAX_CRON_THREADS: 2
            WORKERS: 4
            #LIST_DB: false
            #WITHOUT_DEMO: true
            #PROXY_MODE: true
            AEROO_DOCS_HOST: goro
            LIMIT_TIME_REAL_CRON: 0
            LIMIT_TIME_REAL: 9999
            #UNACCENT: false
            #ODOO_UPGRADE_PATH: /home/odoo/custom/odoo-upgrade
        dns:
            - 172.30.16.10
        networks:
            goro:

volumes:
    pg_data:
    odoo_data:
    default:

networks:
    goro:
        external: false
        name: goro-16
        ipam:
            config:
                - subnet: 172.30.16.0/24

