version: '2.1'
services:
    metabase:
        restart: "always"
        image: metabase/metabase
        environment:

            - MB_DB_TYPE=postgres
            - MB_DB_DBNAME=metabase
            - MB_DB_PORT=5432
            - MB_DB_USER=odoo
            - MB_DB_PASS=odoo
            - MB_DB_HOST=db
        ports:
            - 3000:3000
        networks:
            goro:
        labels:
            - traefik.enable=true
            #- traefik.frontend.port=3000
            - traefik.docker.network=goro

            - traefik.http.routers.metabase.entrypoints=http,https
            - traefik.http.routers.metabase.tls=true
            - traefik.http.routers.metabase.tls.certresolver=le
            - traefik.http.routers.metabase.rule=Host(`metabase.casagoro.com.ar`)
            - traefik.http.routers.metabase.service=metabase@docker
            - traefik.http.routers.metabase.middlewares=gzip
            - traefik.http.services.metabase.loadbalancer.server.port=3000
        depends_on:
            - db
            - dns

    db:
        image: postgres:14
        shm_size: 2gb
        restart: "always"
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - pg_data:/var/lib/postgresql/data/pgdata
        networks:
            goro:
        ports:
           - 54320:5432
    aeroo:
        image: adhoc/aeroo-docs
        restart: unless-stopped
        networks:
            goro:
    dns:
        image: cytopia/bind:alpine-0.30
        environment:
            DNS_A: 'www.casagoro.com.ar=172.30.16.1'
            DNS_FORWARDER: '8.8.8.8,8.8.4.4,127.0.0.11'
        networks:
            goro:
                ipv4_address: 172.30.16.10
    odoo:
        # user: root
        # build:
        #     context: ./data
        #     dockerfile: Dockerfile
        restart: "always"
        image: filoquin/odoo:16.0
        depends_on:
            - db
            - dns
            - aeroo
        volumes:
            - ./custom_modules:/opt/odoo/src/custom-addons
            - default:/home/odoo/src
            - ./odoo_data:/opt/odoo/data
            - ./odoo.conf:/opt/odoo/odoo.conf
        labels:
            # global config
            - traefik.enable=true
            - traefik.docker.network=goro

            # main routers 8069 web rule
            - traefik.http.routers.frontend.entrypoints=http,https
            - traefik.http.routers.frontend.tls=true
            - traefik.http.routers.frontend.tls.certresolver=le
            - traefik.http.routers.frontend.rule=Host(`www.casagoro.com.ar`)
            - traefik.http.routers.frontend.service=frontend@docker
            - traefik.http.routers.frontend.middlewares=gzip
            - traefik.http.services.frontend.loadbalancer.server.port=8069

            # main routers 8072 websocket rule /websocket
            - traefik.http.routers.socket.tls=true
            - traefik.http.routers.socket.entrypoints=http,https
            - traefik.http.routers.socket.rule= Host(`www.casagoro.com.ar`) && Path(`/websocket`)
            - traefik.http.routers.socket.middlewares=upgradeheader,gzip
            - traefik.http.routers.socket.service=socket@docker
            - traefik.http.services.socket.loadbalancer.server.port=8072

            # upgrade headers
            - traefik.http.middlewares.upgradeheader.headers.customRequestHeaders.Upgrade=websocket
            - traefik.http.middlewares.upgradeheader.headers.customRequestHeaders.Connection=Upgrade
            - traefik.http.middlewares.upgradeheader.headers.hostsproxyheaders=websocket,Upgrade

            # gzip compress
            - traefik.http.middlewares.gzip.compress=true

        environment:
            CUSTOM_CONFIG: |-
                [options]
            CUSTOM_REQUIREMTNS: |-
                # custom pip librearies
            CUSTOM_ENTRYPOINT: |-
                #!/bin/bash
                # pip install --user --no-cache-dir -e /home/odoo/custom/odoo
                # pip install --user --no-cache-dir pyopenssl
            DBFILTER: 16.casagoro.com.ar
            MAX_CRON_THREADS: 2
            WORKERS: 0
            #LIST_DB: false
            #WITHOUT_DEMO: true
            #PROXY_MODE: true
            AEROO_DOCS_HOST: goro
            LIMIT_TIME_REAL_CRON: 0
            LIMIT_TIME_REAL: 9999
            PGUSER: odoo
            PGPASSWORD: odoo
            PGHOST: db
            #UNACCENT: false
            #ODOO_UPGRADE_PATH: /home/odoo/custom/odoo-upgrade
        dns:
            - 8.8.8.8
            - 8.8.4.4
            - 172.30.16.10
        networks:
            goro:

volumes:
    pg_data:
    odoo_data:
    default:

networks:
    goro:
        external: true
        name: goro-16
